package constants

const (
	// COMMON
	ERR_COMMON_INTERNAL_SERVER_ERROR  = 500
	ERR_COMMON_FIELD_NOT_FOUND        = 501
	ERR_COMMON_PERMISSION_NOT_FOUND   = 502
	ERR_COMMON_PERMISSION_NOT_ALLOWED = 503
	ERR_COMMON_PROJECT_NOT_FOUND      = 504
	ERR_COMMON_REQUEST_TOO_LARGE      = 505

	// Company
	ERR_COMPANY_NOT_FOUND           = 0
	ERR_COMPANY_NO_PERM_TO_CREATE   = 1
	ERR_COMPANY_NO_PERM_TO_UPDATE   = 2
	ERR_COMPANY_INVALID_ID          = 3
	ERR_COMPANY_GET_ALL_NOT_ALLOWED = 4

	// User
	ERR_USER_CREATION_NOT_ALLOWED = 100
	ERR_USER_NOT_FOUND            = 101
	ERR_USER_WRONG_PASSWORD       = 102
	ERR_USER_WEAK_PASSWORD        = 103
	ERR_USER_ALREADY_EXIST        = 104

	// Project
	ERR_PROJECT_CREATION_NOT_ALLOWED = 200
	ERR_PROJECT_NOT_FOUND            = 204

	// Project Iteration
	ERR_PROJECT_ITERATION_NOT_FOUND          = 250
	ERR_PROJECT_ITERATION_UPLOAD_NOT_ALLOWED = 251
	ERR_PROJECT_ITERATION_EDIT_NOT_ALLOWED   = 252
	ERR_PROJECT_ITERATION_DELETE_NOT_ALLOWED = 253

	// Role
	ERR_ROLE_MANAGEMENT_NOT_ALLOWED    = 300
	ERR_ROLE_USER_OR_ROLE_NOT_FOUND    = 301
	ERR_ROLE_USER_ALREADY_ADDED        = 302
	ERR_ROLE_INVALID_PERMISSION_LEVEL  = 303
	ERR_ROLE_INVALID_PROJECT           = 304
	ERR_ROLE_PERMISSION_ALREADY_ADDED  = 305
	ERR_ROLE_ROLE_OR_PROJECT_NOT_FOUND = 306
	ERR_ROLE_PROJECT_NOT_FOUND         = 307
	ERR_ROLE_PERMISSION_NOT_FOUND      = 308
	ERR_ROLE_NOT_FOUND                 = 309

	// File manager
	ERR_FILE_TYPE_NOT_ALLOWED = 400
)
